apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghumo-duniya
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghumo-duniya
  template:
    metadata:
      labels:
        app: ghumo-duniya
    spec:
      containers:
      - name: ghumo-duniya
        image: unit1998/ghumo_duniya:latest
        imagePullPolicy: Always # <--- ADD THIS LINE
        ports:
        - containerPort: 80